services:
  landing_page:
    container_name: landing_page
    hostname: landing_page
    build:
      context: ..
      dockerfile: ./docker/build.dockerfile
      args:
        - PORT=3000
    expose:
      - 3000
    environment:
      PORT: 3000
    restart: unless-stopped
    networks:
      - ix-nginx-proxy-manager

networks:
  ix-nginx-proxy-manager:
    name: ix-nginx-proxy-manager
    external: true
