name: CD

on:
  workflow_dispatch:
  
jobs:
  cd:
    runs-on: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Down
        run: docker compose -f ./docker/docker-compose.yml down || echo "Nothing to do"

      - name: Up
        run: docker compose -f ./docker/docker-compose.yml up --build -d --wait
